import type { Metadata } from "next";
import { Noto_Serif } from "next/font/google";
import "@/app/_styles/globals.scss";

// import font
const notoSerif = Noto_Serif({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--font-noto-serif",
});

export const metadata: Metadata = {
  title: "Elle Rogers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSerif.variable}>{children}</body>
    </html>
  );
}
